
const phrases = [
  'protect',
  'wilderness',
  'yucca man',
  'cacti',
  'ode to solitude',
  'arroyo',
  'playa',
  'javalina',
  'joshua tree',
  'basin and range',
  'lava tubes',
  'crag',
  'sands of time',
  'blind',
  'grassland',
  'the void',
  'burning bush',
  'the watch',
  'temple of the sun',
  'plateau',
  'cirque',
  'tower',
  'footprints',
  'patina',
  'butte',
  'varnish',
  'escarpment',
  'roadrunner',
  'ecosystem',
  'team buckwheat',
  'wildflowers in the spring',
  'desolation',
  'open range',
  'campfire companion',
  'juniper',
  'scrub oak',
  'spring',
  'boojum',
  'cirrios',
  'irrigation',
  'Gobi',
  'steppe',
  'pitaya',
  'barrel cactus',
  'barren',
  'cholla',
  'greasewood',
  'mesquite',
  'gila',
  'kit fox',
  'Mojave phonebooth',
  'Pichacho',
  'bighorn sheep',
  'Sonora',
  'Chihuahuan',
  'creosote',
  'tarantula',
  'mule deer',
  'clay',
  'wash',
  'desierto',
  'gravel',
  'dusty',
  'dry',
  'yucca',
  'bush',
  'dune',
  'mesa',
  'gypsum',
  'sand',
  'pine',
  'pinon',
  'sweetgrass',
  'flower',
  'erosion',
  'large space',
  'flying saucer',
  'test range',
  'aliens are real',
  'UFO',
  'crater',
  'lake bed',
  'bed rock',
  'shale',
  'flash flood',
  'dry wash',
  'sun',
  'stars',
  'comet',
  'homesteader',
  'dust',
  'goggles',
  'sunburn',
  'burning bush',
  'sacrement',
  `Roy's Motel`,
  'road house',
  'Salton Sea',
  'carry water',
  'Atacama',
  'sagebush expanse',
  'sahara',
  'canyon',
  'coyote',
  'scorpion',
  'centipede',
  'petroglyphs',
  'kalahari',
  'karakum',
  'pictographs',
  'arid lands',
  'aliens',
  'Roswell',
  'Tuscon',
  'chapparal',
  'greys',
  'pueblo',
  'desert oracle',
  'wandering',
  'seco',
  'winds',
  'grand vista',
  'controversial monolith',
  'basin',
  'valley',
  'aquifer',
  'coyote melon',
  'tortoise',
  'hare',
  'cryptobiotic crusts',
  'mountain goat',
  'monster',
  'monsoon',
  'rainshadow',
  'shade',
  'altitude sickness',
  'salt',
  'dry lake',
  'objects',
  'earth art',
  'hawk',
  'cactus',
  'alluvial fan',
  'namib',
  'cave',
  'coulee',
  'ocotillo',
  'poppy',
  'dandelion',
  'marigold',
  'danakil',
  'maripose lily',
  'cyprus',
  'ridgeline',
  'depression',
  'alkali',
  'walker',
  'kangaroo rat',
  'shrub',
  'rocks',
  'walking',
  'crawling',
  'white sky',
  'scrub',
  'vast',
  'unknown',
  'thirst',
  'stay with the car',
  'empty',
  'stone',
  'stones',
  'well',
  'ants',
  'apparition',
  'visions',
  'mirage',
  'scalding',
  'concrete',
  'baked',
  'boulder field',
  'boulder',
  'garbage',
  'change',
  'burro',
  'goat',
  'quail',
  'dove',
  'branch',
  'blacktop',
  'motorcycle',
  'giant rock',
  'black rock canyon',
  'colorado plateau',
  'snowbird',
  'dry heat',
  'oasis',
  'swamp cooler',
  'fan hum',
  'cardboard',
  'sonoran dog',
  'mojave',
  'adobe',
  'biome',
  'harsh',
  'drought',
  'greasewood',
  'Needles',
  'Blythe',
  'palm oasis',
  'palm',
  'vista',
  'Death Valley',
  'panamint',
  'mining',
  'chlorax',
  'wells',
  'stovepipe',
  'open space',
  'hopes and dreams',
  'rubble',
  'stake',
  'desert rat',
  'palo verde',
  'kangaroo rat',
  'mountain lion',
  'desert wilderness',
  'strange and unusual',
  'unexplained',
  'eerie',
  'paranormal phenomenon',
  'ranch',
  'cattle',
  'rancher',
  'cow pucks',
  'palo santo',
  'petrified wood',
  'sage',
  'bristlecone',
  'jackrabbit',
  'antelope',
  'dust in your nose',
  'darkling beetle',
  'lizard',
  'snake',
  'rattle',
  'chapped lips',
  'poppy',
  'lupin',
  'marigold',
  'granite',
  'epoch',
  'lava tube',
  'depot',
  'intrusion',
  'subduction',
  'basalt',
  'volcano',
  'lava',
  'dome',
  'tamarisk',
  'fan palm',
  'fault lines',
  'icebox',
  'cooler',
  'tire hum',
  'whistle',
  'chia flower',
  'rift',
  'salt flat',
  'ancient sea',
  'voices in the hills',
  'ancient',
  'amboy crater',
  `Roy's`,
  'sizzling skin',
  'lomas',
  'flamingo',
  'cardon',
  'drainage',
  'scramble',
  'empty head',
  'wind',
  'ears ringing',
  'sacrement',
  'seeing lights',
  'fire in the sky'
]

const shuffle = (array: string[]) => {
  let currentIndex = array.length,
    temporaryValue,
    randomIndex

  // While there remain elements to shuffle...
  while (0 !== currentIndex) {
    // Pick a remaining element...
    randomIndex = Math.floor(Math.random() * currentIndex)
    currentIndex -= 1

    // And swap it with the current element.
    temporaryValue = array[currentIndex]
    array[currentIndex] = array[randomIndex]
    array[randomIndex] = temporaryValue
  }

  return array
}

const makeSentence = () => {
  const shuffledPhrases = shuffle(phrases)
  let sentence =
    // pass random number between 3-9 for number of strings in sentence
    shuffledPhrases.slice(0, Math.random() * (9 - 3) + 6).join(' ') + '. '
  sentence = sentence.charAt(0).toUpperCase() + sentence.slice(1)
  return sentence
}

const makeParagraph = (sentences: number) => {
  let paragraph = []
  for (let i = 0; i < sentences; i++) {
    paragraph.push(makeSentence())
  }
  return paragraph.join('')
}

export const generateLorem = (paragraphs: number) => {
  let lorem = []
  for (let i = 0; i < paragraphs; i++) {
    // pass random number between 2-6 for number of sentences in paragraph
    lorem.push(`<p>${makeParagraph(Math.round(Math.random() * (6 - 2) + 3))}</p>`)
  }
  return lorem.join('')
}